name: Beans

options:
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  Beans:
    type: application
    platform: iOS
    sources: [Beans]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beans.app
        MARKETING_VERSION: "1.6"
        CURRENT_PROJECT_VERSION: "37"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_OBJC_BRIDGING_HEADER: Beans/Beans-Bridging-Header.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Beans/Info.plist
      properties:
        CFBundleDisplayName: BMusic
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UIBackgroundModes: [audio]
        UILaunchScreen:
          UIImageName: LaunchBackground
          UIColorName: LaunchBackgroundColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        CADisableMinimumFrameDurationOnPhone: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        CFBundleDocumentTypes:
          - CFBundleTypeName: JSON Catalog
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.json
        UIApplicationShortcutItems:
          - UIApplicationShortcutItemType: com.beans.app.playLiked
            UIApplicationShortcutItemTitle: 播放喜欢的音乐
            UIApplicationShortcutItemIconSymbolName: heart.fill
          - UIApplicationShortcutItemType: com.beans.app.playRecent
            UIApplicationShortcutItemTitle: 播放最近播放的音乐
            UIApplicationShortcutItemIconSymbolName: clock.arrow.circlepath

schemes:
  Beans:
    build:
      targets:
        Beans: all
    run:
      config: Debug
    archive:
      config: Release
